### ISSUE TITLE
Parse issue: 8115-corelight-ecs-user_agent-original-enrich-filter.conf

### ISSUE THREAD

**Issue by hsportel** [corelight/ecs-logstash-mappings#32]
There is an parse issue with this pipeline in combination with ELK 8.7
There a no HTTP logs. Also no logs in "corelight parse failures" index?

Logstash log are loaded with these lines:
"status"=>400, "error" "failed to parse field **[user_agent.device.name**] of type [keyword] type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT

After disabling this pipeline http logs will come in again, but with no user_agent enrichment's.

**Comment by brasitech** [comment]
try with uncommenting this line:
https://github.com/corelight/ecs-logstash-mappings/blob/5dac91c8497aec601e0cd60fe3d833160ba288e4/pipeline/8115-corelight-ecs-user_agent-original-enrich-filter.conf#L28

**Comment by hsportel** [comment]
Thnx, That does the trick.
I already uncommented in _0002-corelight-ecs-tcp-input.conf_, not realizing there other conf files with that same line.
