### ISSUE TITLE
Config has duplicate Ids

### ISSUE THREAD

**Issue by MarkVanAcker** [corelight/ecs-logstash-mappings#36]
Hi,

I'm trying to update our pipeline to the latest version (28) and I'm getting a 
`Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:logstash-7.16.2-logs-staging-csoc-01a-zeek-conveyor, :exception=>"Java::JavaLang::IllegalArgumentException", :message=>"org.logstash.config.ir.InvalidIRException: Config has duplicate Ids: \nID: filter-ruby-060bbdc7d94a`.

In this case it's a conflict between an id in `8115-corelight-ecs-smtp-subject-enrich-filter.conf` and `8115-corelight-ecs-email-subject-enrich-filter.conf`. I have noticed a few more conflicts like this in other files.

**Comment by neu5ron** [comment]
there should not be a file 8115-corelight-ecs-smtp-subject-enrich-filter.conf in the latest (newrelease), is possibly combining the previous one and new one?

If you are open, you can use mine that is a little bit a head right now:
https://github.com/brasitech/ecs-templates/tree/latest

@hunter32me what do you think about a fresh repo.. making `main` only have the "new" release. or any other branch for that mater. I started using `latest` in mine

@

**Comment by hunter32me** [comment]
> Hi,
> 
> I'm trying to update our pipeline to the latest version (28) and I'm getting a `Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:logstash-7.16.2-logs-staging-csoc-01a-zeek-conveyor, :exception=>"Java::JavaLang::IllegalArgumentException", :message=>"org.logstash.config.ir.InvalidIRException: Config has duplicate Ids: \nID: filter-ruby-060bbdc7d94a`.
> 
> In this case it's a conflict between an id in `8115-corelight-ecs-smtp-subject-enrich-filter.conf` and `8115-corelight-ecs-email-subject-enrich-filter.conf`. I have noticed a few more conflicts like this in other files.

When you copy the pipeline over, did you copy over the pipelines in the same directory as the existing one? If so, I will update the document steps, as that is something we missed. It will not overwrite or remove pipelines that are not in the new release. If this is the case sorry for not catching this.

**Comment by MarkVanAcker** [comment]
Hello,

My apologies, I mixed up the two versions indeed. 
I will close this ticket. 

And thank you @neu5ron I will have a look at your repo.
