### ISSUE TITLE
[@metadata][temporary_metadata_index_strategy] should be documented for data streams

### ISSUE THREAD

**Issue by brsolomon-deloitte** [corelight/ecs-logstash-mappings#7]
It appears that `add_field { [@metadata][temporary_metadata_index_strategy] => "datastream" }` is necessary for enabling Elasticsearch data streams, but is entirely undocumented.

Numerous pipelines check `if [@metadata][temporary_metadata_index_strategy] == "datastream" {`, but the need to set that field in input configuration is undocumented.

Without this field set, Logstash Elasticsearch output's `data_stream_auto_routing` won't work since `data_stream` is not set in the output JSON.

**Comment by brasitech** [comment]
Thank you for the continuous feedback, documentation for this is needed and in the works.

**Comment by brsolomon-deloitte** [comment]
Bump

**Comment by hunter32me** [comment]
Updated the installer script to do this when a Datastream Template is applied to the unit.
